{
 "title": "Hourly Dashboard",
 "time": { "from": "2025-01-01T00:00:00.000Z", "to": "2025-01-31T23:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "station",
    "query": {
     "query": "SELECT wsid FROM station.station"
    }
   },
   {
    "name": "year",
    "query": {
     "query": "SELECT year FROM weather.yearly"
    }
   },
   {
    "name": "month",
    "label": "month",
    "query": "01, 02, 03, 04, 05, 06, 07, 08, 09, 10, 11, 12"
   }
  ]
 },
 "panels": [
  { "title": "Meta Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT wsid FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT wsid FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT elevation FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT  latitude FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT longitude FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT begin_date FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT end_date FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  { "title": "Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT name FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "target": "SELECT wsid, elevation, latitude, longitude, begin_date, end_date FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT country, official_name_en, capital, sub_region, region, continent FROM station.country WHERE wsid = '${station}' ALLOW FILTERING;"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Observations",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "target": "SELECT wsid, year, m1, m2, m3,m4, m5, m6, m7, m8,m9, m10, m11, m12 FROM station.history WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "History Record (Monthly)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT AVG(temperature) / 10.0, MIN(temperature)/ 10.0, MAX(temperature)/ 10.0, AVG(dewpoint)/ 10.0, MIN(dewpoint)/ 10.0, MAX(dewpoint)/ 10.0, AVG(pressure) / 10.0, MIN(pressure)/ 10.0, MAX(pressure)/ 10.0, AVG(wind_speed) / 10.0, SUM(one_hour_precip)/ 10.0 FROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Daily Summary",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, temperature_avg / 10.0, dewpoint_avg/ 10.0, pressure_avg/ 10.0, wind_direction, wind_speed_avg/ 10.0, sky_condition, precipitation/ 10.0\nFROM weather.daily WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Observations by Day",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "target": "SELECT day\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Hourly Observation",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, temperature / 10.0, dewpoint/ 10.0, pressure/ 10.0, wind_direction, wind_speed/ 10.0, sky_condition\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, temperature / 10.0\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, dewpoint / 10.0\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, wind_speed / 10.0\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Sea Level Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, pressure / 10.0\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  },
  {
   "title": "Sky Condition",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp,  sky_condition\nFROM weather.hourly WHERE wsid = '${station}' AND year = ${year} AND month = ${month}"
    }
   ]
  }
 ]
}