{
 "title": "Summary Dashboard",
 "time": { "from": "now/y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "station",
    "query": {
     "query": "SELECT wsid FROM station.station"
    }
   }
  ]
 },
 "panels": [
  { "title": "Meta Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "SELECT wsid, year, month, day, hour FROM weather.hourly WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "target": "SELECT wsid, year, month, day FROM weather.daily WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT wsid FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT  latitude FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT longitude FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT end_date FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    {
     "target": "SELECT wsid, year, month FROM weather.monthly WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "targets": [
    {
     "target": "SELECT wsid, year FROM weather.yearly WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT wsid FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT country, official_name_en FROM station.country WHERE wsid = '${station}' ALLOW FILTERING;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT elevation FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT begin_date FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  { "title": "Location", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT name FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "target": "SELECT wsid, elevation, latitude, longitude, begin_date, end_date FROM station.station WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT country, official_name_en, capital, sub_region, region, continent FROM station.country WHERE wsid = '${station}' ALLOW FILTERING;"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Observations",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "SELECT wsid, year, m1, m2, m3,m4, m5, m6, m7, m8,m9, m10, m11, m12 FROM station.history WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Yearly Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "SELECT wsid,\ntemperature_avg / 10.0,\n    temperature_min / 10.0,\n    temperature_max / 10.0,\n    dewpoint_avg / 10.0,\n    dewpoint_min / 10.0,\n    dewpoint_max / 10.0,\n    pressure_avg / 10.0,\n    pressure_min / 10.0,\n    pressure_max / 10.0,\n    wind_speed_avg / 10.0,\n    wind_speed_min / 10.0,\n    wind_speed_max / 10.0,\n    precipitation/ 10.0\nFROM weather.yearly WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Daily Summary",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, temperature_avg / 10.0, temperature_min/10.0, temperature_max/10.0, dewpoint_avg/ 10.0, dewpoint_min/10.0, dewpoint_max/10.0, pressure_avg/ 10.0,pressure_min/10.0, pressure_max/10.0, wind_direction, wind_speed_avg/ 10.0, wind_speed_min/10.0, wind_speed_max/10.0, sky_condition, precipitation/ 10.0\nFROM weather.yearly WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Monthly Summary",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, temperature_avg / 10.0, temperature_min/10.0, temperature_max/10.0, dewpoint_avg/ 10.0, dewpoint_min/10.0, dewpoint_max/10.0, pressure_avg/ 10.0,pressure_min/10.0, pressure_max/10.0, wind_direction, wind_speed_avg/ 10.0, wind_speed_min/10.0, wind_speed_max/10.0, sky_condition, precipitation/ 10.0\nFROM weather.monthly WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, temperature_avg / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, temperature_min / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, temperature_max / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Dewpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, dewpoint_avg / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, dewpoint_min / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, dewpoint_max / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, wind_speed_avg / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, wind_speed_min / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, wind_speed_max / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp, pressure_avg / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, pressure_min / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    },
    {
     "target": "SELECT wsid, timestamp, pressure_max / 10.0\nFROM weather.daily WHERE wsid = '${station}'"
    }
   ]
  },
  {
   "title": "Sky Condition",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {
     "target": "SELECT wsid, timestamp,  sky_condition\nFROM weather.hourly WHERE wsid = '${station}'"
    }
   ]
  }
 ]
}